services:
  kafka-producer-cam1:
    build:
      context: ./data-pipeline/kafka-component
      dockerfile: Dockerfile.producer
    environment:
      - CAMERA_ID=cam1
      - CONFIG_FILE=/app/config.json
    container_name: cam1_producer
    volumes:
      - ./data-pipeline/kafka-component/producer_config.json:/app/config.json:ro
    networks:
      - internal_net
  
  kafka-producer-cam2:
    build:
      context: ./data-pipeline/kafka-component
      dockerfile: Dockerfile.producer
    environment:
      - CAMERA_ID=cam2
      - CONFIG_FILE=/app/config.json
    container_name: cam2_producer
    volumes:
      - ./data-pipeline/kafka-component/producer_config.json:/app/config.json:ro
    networks:
      - internal_net

networks:
  internal_net:
    external: true  