apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: default
data:
  haproxy.cfg: |
    global
        daemon
        maxconn 4096

    defaults
        log global
        mode tcp
        option tcplog
        timeout connect 5s
        timeout client 50s
        timeout server 50s

    frontend rtmp_front
        bind *:1935
        default_backend rtmp_backend

    backend rtmp_backend
        mode tcp
        balance source
        server rtsp1 rtsp-server-1:1935 check inter 2s fall 3 rise 2
        server rtsp2 rtsp-server-2:1935 check inter 2s fall 3 rise 2
        server rtsp3 rtsp-server-3:1935 check inter 2s fall 3 rise 2

    listen stats
        bind *:8888
        mode http
        stats enable
        stats uri /
        stats refresh 5s
        stats show-node