---
apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config
  namespace: default 
data:
  config.json: |-
    {
      "mediamtx_servers": [
          {"server_name": "rtsp_server_1", "api_port": 9997, "rtmp_port": 1935},
          {"server_name": "rtsp_server_2", "api_port": 9997, "rtmp_port": 1935},
          {"server_name": "rtsp_server_3", "api_port": 9997, "rtmp_port": 1935}
      ],
      "kafka_bootstrap_servers": ["kafka-bootstrap:9092"],
      "segment_duration": 10,
      "chunk_size": 524288,
      "debug": false
    }