---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-repo-pv
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /model_repository
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-repo-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual