---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-gpu
      containers:
      - name: backend
        image: lhn102/traffic-fastapi-backend:latest
        ports:
        - containerPort: 8000
          protocol: TCP
          name: http
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-bootstrap:9092"
      restartPolicy: Always