---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: default
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-normal
      initContainers:
      - name: init-broker-id
        image: busybox:1.36
        command:
        - sh
        - -c
        - |          
          INDEX=$(echo $POD_NAME | grep -o '[0-9]\+$')
          BROKER_ID=$((INDEX + 1))
          echo "broker.id=$BROKER_ID" > /etc/kafka/broker-id
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: kafka-config
          mountPath: /etc/kafka
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.9.0
        command:
        - sh
        - -c
        - |
          export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://$POD_NAME.kafka.default.svc.cluster.local:9092"
          /etc/confluent/docker/run
        ports:
        - containerPort: 9092
          protocol: TCP
          name: internal
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_NUM_PARTITIONS
          value: "3"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
        - name: kafka-config
          mountPath: /etc/kafka
      volumes:
      - name: kafka-config
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: local-path