apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-normal
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.9.0
        ports:
        - containerPort: 2181
          protocol: TCP
          name: client
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"