apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: default
spec:
  selector:
    app: haproxy
  ports:
  - name: rtmp
    port: 1935
    targetPort: 1935
    protocol: TCP
    nodePort: 31000
  type: NodePort