---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: default
spec:
  selector:
    app: kafka
  ports:
  - name: internal
    port: 9092
    targetPort: 9092
    protocol: TCP
  clusterIP: None  
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-bootstrap
  namespace: default
spec:
  selector:
    app: kafka
  ports:
  - name: internal
    port: 9092
    targetPort: 9092
    protocol: TCP
  type: ClusterIP