---
apiVersion: v1
kind: Service
metadata:
  name: rtsp-server-1
  namespace: default
spec:
  selector:
    app: rtsp-server-1
  ports:
  - name: rtmp
    port: 1935
    targetPort: 1935
    protocol: TCP
  - name: api
    port: 9997
    targetPort: 9997
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rtsp-server-2
  namespace: default
spec:
  selector:
    app: rtsp-server-2
  ports:
  - name: rtmp
    port: 1935
    targetPort: 1935
    protocol: TCP
  - name: api
    port: 9997
    targetPort: 9997
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rtsp-server-3
  namespace: default
spec:
  selector:
    app: rtsp-server-3
  ports:
  - name: rtmp
    port: 1935
    targetPort: 1935
    protocol: TCP
  - name: api
    port: 9997
    targetPort: 9997
    protocol: TCP
  type: ClusterIP