---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: default
spec:
  selector:
    app: zookeeper
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    protocol: TCP
  type: ClusterIP